image: gradle:5.6-jdk8

before_script:
  - echo "artifactory_contextUrl=$CI_ARTIFACTORY_URL" >> gradle.properties
  - echo "artifactory_user=$CI_ARTIFACTORY_USER" >> gradle.properties
  - echo "artifactory_password=$CI_ARTIFACTORY_PASSWORD" >> gradle.properties
  - echo "artifactory_repo=gradle-dev-local" >> gradle.properties
  - cat gradle.properties

build-master:
  stage: build
  script:
    - gradle build ArtifactoryPublish
  only:
    - master