# =========================================================================================================== #                                                                 #
# host: url of the db (set localhost for local db)                                                            #
# login: login for connect need have permission to create and edit table                                      #
# password: password of the login                                                                             #
# dbname: name of the db need be created always                                                               #
# system: mysql -
# =========================================================================================================== #
db: # NO value here !
  host: ''
  login: ''
  password: ''
  dbname: ''
  system: 'mysql'
  connexion_args: '?allowMultiQueries=true&useSSL=false'

# =========================================================================================================== #
# host: url of the frs (set 127.0.0.1 for local db)                                                            #
# password: password for log          (def 4514)                                                              #
# port:port listening by frs                                                                                    #
# timeout: timeout time (def 5000)                                                                             #
# =========================================================================================================== #
frs: # NO value Here
  host: ''
  port: 4514
  password: ''
  timeout: 5000

server_motd: "&9Mine&6Tasia&7>> %s"

cache:
  user: 2

# =========================================================================================================== #
# time in second between player count update                                                                  #
# =========================================================================================================== #
player_count_update: 30